### ISSUE TITLE
点击清除病毒本体报错

### ISSUE THREAD

**Issue by UCHIHAHA103** [cpcgskill/VirusKiller_240429#2]
![image](https://github.com/cpcgskill/VirusKiller_240429/assets/61904674/92a15279-36ad-4f17-8dfd-d7f623c77530)
大佬看看，这个是正常的吗

**Comment by cpcgskill** [comment]
没有修改文件的权限，以管理员身份打开试试

**Comment by UCHIHAHA103** [comment]
![image](https://github.com/cpcgskill/VirusKiller_240429/assets/61904674/ed78d715-0f41-4f25-bdbb-9c69a0a8cd38)
我用管理员打开maya，成功运行软件并提示病毒已清理，但是userSetup.mel显示还是有病毒信息，是正常的吗

**Comment by cpcgskill** [comment]
你把运行时的截图发我看看

**Comment by cpcgskill** [comment]
我检查了一下代码你现在新开maya重新运行一遍，应该会提示：“发现病毒, 但未找到病毒路径”

**Comment by UCHIHAHA103** [comment]
> 你把运行时的截图发我看看

![recording](https://github.com/cpcgskill/VirusKiller_240429/assets/61904674/24a3286a-e60b-458b-a80c-ae695b1e859b)

**Comment by UCHIHAHA103** [comment]
貌似工具没有修改userSetup.mel
![image](https://github.com/cpcgskill/VirusKiller_240429/assets/61904674/1dad3747-67c9-4cb3-89d0-4ab402edd5e8)

**Comment by cpcgskill** [comment]
是的这是个bug，不过病毒确实无法运行了，因为这个文件是去尝试执行病毒本体。然后病毒本体已经被删除了。

**Comment by UCHIHAHA103** [comment]
> 是的这是个bug，不过病毒确实无法运行了，因为这个文件是去尝试执行病毒本体。然后病毒本体已经被删除了。

大佬，我还想确认一下，就是说userSetup.mel有这串病毒代码，也不影响吗

**Comment by cpcgskill** [comment]
是的，不过以防万一等我修复bug之后你可以重新跑一遍

**Comment by UCHIHAHA103** [comment]
可以支持批量操作吗，文件数量太多了~

**Comment by cpcgskill** [comment]
已经有了
