### ISSUE TITLE
大佬，我下载的最新压缩包文件里没有install.mel文件

### ISSUE THREAD

**Issue by ZX43** [cpcgskill/VirusKiller_240429#4]

**Comment by ZX43** [comment]
![A](https://github.com/cpcgskill/VirusKiller_240429/assets/168514514/9552416a-784d-41e9-85a3-dc0dba842eff)

**Comment by HANlengxuan** [comment]
我这下载完也是 卡在第一步了

**Comment by cpcgskill** [comment]
目前最新版本是0.1.3,0.1.0没有install.mel，后面的版本应该都清理了

**Comment by cpcgskill** [comment]
目前最新版本是0.1.3,0.1.0没有install.mel，后面的版本应该都添加了

**Comment by HANlengxuan** [comment]
![wrq](https://github.com/cpcgskill/VirusKiller_240429/assets/81637247/7f370679-b70d-4681-b350-604635b59714)
大佬刚下载的0.1.4也没有install.mel

**Comment by cpcgskill** [comment]
下载插件文件，两位可能都下载为源代码文件了

**Comment by HANlengxuan** [comment]
不好意思 让大佬见笑了 没用过这个 下载错了 哈哈哈。。。。

**Comment by cpcgskill** [comment]
没事没事 ~
